"""AutoGenerated with:
python -m autopipe.partition new_t5 --model_name_or_path t5-base --t5_task squad1 --lmhead --n_iter 3 --analysis_batch_size 2 --partitioning_batch_size 2 --stateless_tied --lmhead --n_partitions 8 --L 16 --max_seq_length 512 --answer_max_seq_length 4 --partitioning_method mpipe --save_memory_mode --output_file lg --special_blocks T5Block --basic_blocks T5Block
"""
import torch.linalg
import torch.functional
import torch
import math
import torch.fft
import torch.nn.functional
from torch import Tensor
import torch.nn as nn
from itertools import chain
from typing import Optional, Tuple, Iterator, Iterable, OrderedDict, Dict
import collections

from typing import Type
from models.normal.NLP_models.stateless import StatelessEmbedding
from torch.nn.modules.linear import Linear
from torch.nn.modules.dropout import Dropout
from models.new_t5_example.modeling_t5 import T5Block
from models.new_t5_example.modeling_t5 import T5LayerNorm
# this is an auto generated file do not edit unless you know what you are doing


# partition adjacency
# model inputs {0, 10, 6}
# partition 0 {'inputs': {'attention_mask', 'decoder_attention_mask', 'input_ids', 'decoder_input_ids'}, 'outputs': {1, 6}}
# partition 1 {'inputs': {0}, 'outputs': {2, 3, 4, 5}}
# partition 2 {'inputs': {1}, 'outputs': {3}}
# partition 3 {'inputs': {1, 2}, 'outputs': {4}}
# partition 4 {'inputs': {1, 3}, 'outputs': {5}}
# partition 5 {'inputs': {1, 4}, 'outputs': {8, 9, 6, 7}}
# partition 6 {'inputs': {0, 'attention_mask', 5, 'decoder_input_ids'}, 'outputs': {8, 9, 7}}
# partition 7 {'inputs': {5, 6}, 'outputs': {8}}
# partition 8 {'inputs': {5, 6, 7}, 'outputs': {9}}
# partition 9 {'inputs': {8, 5, 6}, 'outputs': {10}}
# partition 10 {'inputs': {9, 'labels'}, 'outputs': {'output'}}
# model outputs {10}


def create_pipeline_configuration(DEBUG=False, batch_size=2):
    config = {
        'batch_dim': 0,
        'depth': 10000,
        'basic_blocks': (StatelessEmbedding,Linear,Dropout,T5Block,T5LayerNorm),
        'model_inputs': {
            'attention_mask': {
                'shape': torch.Size([2, 512]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0, 6]},
            'decoder_attention_mask': {
                'shape': torch.Size([2, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0]},
            'decoder_input_ids': {
                'shape': torch.Size([2, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0, 6]},
            'input_ids': {
                'shape': torch.Size([2, 512]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0]},
            'labels': {
                'shape': torch.Size([2, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [10]}},
        'model_outputs': {
            'T5ForConditionalGeneration/torch.nn.functional::cross_entropy_426': {
                'shape': torch.Size([1]),
                'dtype': torch.float32,
                'is_batched': False,
                'created_by': 10}},
        'stages': {
            0: {
                'stage_cls': Partition0,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([2, 512]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_attention_mask': {
                        'shape': torch.Size([2, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_input_ids': {
                        'shape': torch.Size([2, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'input_ids': {
                        'shape': torch.Size([2, 512]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1}},
                'outputs': {
                    'T5ForConditionalGeneration/Parameter[shared_embed_weight]': {
                        'shape': torch.Size([32100, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/float::__sub___17': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Size::__getitem___216': {
                        'shape': None,
                        'dtype': int,
                        'req_grad': False,
                        'is_batched': False,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/float::__sub___244': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [6]}},
                'devices': ['cpu' if DEBUG else 'cuda:0'],
                'stage_depth': 10},
            1: {
                'stage_cls': Partition1,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/float::__sub___17': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_2': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [2]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___64': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___66': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]}},
                'devices': ['cpu' if DEBUG else 'cuda:1'],
                'stage_depth': 9},
            2: {
                'stage_cls': Partition2,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_2': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___64': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___66': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_3': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [3]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___109': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___111': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]}},
                'devices': ['cpu' if DEBUG else 'cuda:2'],
                'stage_depth': 8},
            3: {
                'stage_cls': Partition3,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_3': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___109': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___111': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_4': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___154': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___156': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]}},
                'devices': ['cpu' if DEBUG else 'cuda:3'],
                'stage_depth': 7},
            4: {
                'stage_cls': Partition4,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_4': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___154': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___156': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_5': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___184': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___186': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]}},
                'devices': ['cpu' if DEBUG else 'cuda:4'],
                'stage_depth': 6},
            5: {
                'stage_cls': Partition5,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_5': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___184': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___186': {
                        'shape': torch.Size([2, 12, 512, 512]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]}},
                'devices': ['cpu' if DEBUG else 'cuda:5'],
                'stage_depth': 5},
            6: {
                'stage_cls': Partition6,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([2, 512]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_input_ids': {
                        'shape': torch.Size([2, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/Parameter[shared_embed_weight]': {
                        'shape': torch.Size([32100, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Size::__getitem___216': {
                        'shape': None,
                        'dtype': int,
                        'req_grad': False,
                        'is_batched': False,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[decoder]/float::__sub___244': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_7': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_7': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___318': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___320': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___322': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]}},
                'devices': ['cpu' if DEBUG else 'cuda:6'],
                'stage_depth': 4},
            7: {
                'stage_cls': Partition7,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_7': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_7': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___318': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___320': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___322': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_8': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [8]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_8': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [8]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_8': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [8]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___344': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [8]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___346': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [8]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___348': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [8]}},
                'devices': ['cpu' if DEBUG else 'cuda:7'],
                'stage_depth': 3},
            8: {
                'stage_cls': Partition8,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_8': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 7},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_8': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 7},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_8': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 7},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___344': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 7},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___346': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 7},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___348': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 7}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_9': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [9]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_9': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [9]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_9': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [9]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___383': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [9]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___385': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [9]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___387': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [9]}},
                'devices': ['cpu' if DEBUG else 'cuda:8'],
                'stage_depth': 2},
            9: {
                'stage_cls': Partition9,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_9': {
                        'shape': torch.Size([2, 512, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 8},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246_9': {
                        'shape': torch.Size([2, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 8},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254_9': {
                        'shape': torch.Size([2, 1, 1, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 8},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___383': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 8},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___385': {
                        'shape': torch.Size([2, 12, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 8},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___387': {
                        'shape': torch.Size([2, 12, 4, 512]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 8}},
                'outputs': {
                    'T5ForConditionalGeneration/Tensor::__mul___413': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [10]}},
                'devices': ['cpu' if DEBUG else 'cuda:9'],
                'stage_depth': 1},
            10: {
                'stage_cls': Partition10,
                'inputs': {
                    'labels': {
                        'shape': torch.Size([2, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/Tensor::__mul___413': {
                        'shape': torch.Size([2, 4, 768]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 9}},
                'outputs': {
                    'T5ForConditionalGeneration/torch.nn.functional::cross_entropy_426': {
                        'shape': torch.Size([1]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'used_by': [-1]}},
                'devices': ['cpu' if DEBUG else 'cuda:10'],
                'stage_depth': 0}},
        'stage_to_device_map': [0, 1, 2, 3, 2, 3, 4, 5, 6, 7, 1]}
    
    
    # switching batch size
    batch_dim = config['batch_dim']
    for d in chain(config['model_inputs'].values(),config['model_outputs'].values()):
        if d['is_batched']:
            shape = d['shape']
            d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    for s in config['stages'].values():
        for d in chain(s['inputs'].values(),s['outputs'].values()):
            if d['is_batched']:
                shape = d['shape']
                d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    return config

class Partition0(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
        ]
    TENSORS = [
            'T5ForConditionalGeneration/Parameter[shared_embed_weight]',
        ]
    def __init__(self, layers, tensors, device='cuda:0'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1]
        self.lookup = {'l_0': 'encoder.embed_tokens',
                        'l_1': 'encoder.dropout',
                        'p_0': 'shared_embed_weight'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_1
        # T5ForConditionalGeneration/Parameter[shared_embed_weight] <=> self.p_0
        # input0 <=> attention_mask
        # input1 <=> decoder_attention_mask
        # input2 <=> decoder_input_ids
        # input3 <=> input_ids
        attention_mask, decoder_attention_mask, decoder_input_ids, input_ids = unflatten(args, self.input_structure)
        t_0 = decoder_input_ids.size()
        t_1 = input_ids.size()
        t_1 = t_1[-1]
        t_1 = input_ids.view(-1, t_1)
        t_1 = self.l_0(self.p_0, t_1)
        t_1 = self.l_1(t_1)
        t_2 = attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_2 = t_2.to(dtype=torch.float32)
        t_2 = 1.0 - t_2
        t_3 = t_0[-1]
        t_4 = t_0[0]
        t_0 = t_0[1]
        t_5 = torch.arange(t_0, device=self.device)
        t_6 = t_5[(None, None, slice(None, None, None))]
        t_0 = t_6.repeat(t_4, t_0, 1)
        t_5 = t_5[(None, slice(None, None, None), None)]
        t_5 = t_0 <= t_5
        t_0 = decoder_attention_mask.dtype
        t_0 = t_5.to(t_0)
        t_0 = t_0[(slice(None, None, None), None, slice(None, None, None), slice(None, None, None))]
        t_5 = decoder_attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_5 = t_0 * t_5
        t_5 = t_5.to(dtype=torch.float32)
        t_5 = 1.0 - t_5
        # Returning:
        # T5ForConditionalGeneration/Parameter[shared_embed_weight]
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[encoder]/float::__sub___17
        # T5ForConditionalGeneration/T5Stack[decoder]/Size::__getitem___216
        # T5ForConditionalGeneration/T5Stack[decoder]/float::__sub___244
        return list(flatten((self.p_0, t_1, t_2, t_3, t_5)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition1(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[0]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[2]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:1'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1]
        self.lookup = {'l_0': 'encoder.block.0',
                        'l_1': 'encoder.block.1',
                        'l_2': 'encoder.block.2'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[0] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[1] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[2] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/float::__sub___17 <=> x1
        x0, x1 = unflatten(args, self.input_structure)
        t_0 = x1 * -10000.0
        t_1 = self.l_0(x0, attention_mask=t_0, position_bias=None, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_2 = t_1[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_1[2]
        t_1 = self.l_1(t_2, attention_mask=t_0, position_bias=t_1, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_2 = t_1[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_1[2]
        t_1 = self.l_2(t_2, attention_mask=t_0, position_bias=t_1, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_2 = t_1[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_1[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___64
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___66
        return list(flatten((t_0, t_2, t_1)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition2(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[3]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[4]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[5]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:2'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.3',
                        'l_1': 'encoder.block.4',
                        'l_2': 'encoder.block.5'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[3] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[4] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[5] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___64 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___66 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___109
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___111
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition3(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[6]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[7]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[8]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:3'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.6',
                        'l_1': 'encoder.block.7',
                        'l_2': 'encoder.block.8'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[6] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[7] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[8] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___109 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___111 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___154
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___156
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition4(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[9]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[10]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:4'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.9',
                        'l_1': 'encoder.block.10'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[9] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[10] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___154 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___156 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___184
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___186
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition5(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[11]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:5'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.11',
                        'l_1': 'encoder.final_layer_norm',
                        'l_2': 'encoder.dropout'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[11] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___184 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___186 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_0 = t_0[slice(None, 2, None)]
        t_0 = t_0[0]
        t_0 = self.l_1(t_0)
        t_0 = self.l_2(t_0)
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition6(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[0]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[2]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[3]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[4]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:6'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.embed_tokens',
                        'l_1': 'decoder.dropout',
                        'l_2': 'decoder.block.0',
                        'l_3': 'decoder.block.1',
                        'l_4': 'decoder.block.2',
                        'l_5': 'decoder.block.3',
                        'l_6': 'decoder.block.4'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[0] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[1] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[2] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[3] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[4] <=> self.l_6
        # input0 <=> attention_mask
        # input2 <=> decoder_input_ids
        # T5ForConditionalGeneration/Parameter[shared_embed_weight] <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Size::__getitem___216 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/float::__sub___244 <=> x3
        attention_mask, decoder_input_ids, x0, x1, x2, x3 = unflatten(args, self.input_structure)
        t_0 = decoder_input_ids.view(-1, x2)
        t_0 = self.l_0(x0, t_0)
        t_0 = self.l_1(t_0)
        t_1 = x3 * -10000.0
        t_2 = attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_2 = t_2.to(dtype=torch.float32)
        t_2 = 1.0 - t_2
        t_2 = t_2 * -1000000000.0
        t_0 = self.l_2(t_0, attention_mask=t_1, position_bias=None, encoder_attention_mask=t_2, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x1)
        t_3 = t_0[slice(None, 2, None)]
        t_3 = t_3[0]
        t_4 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_3(t_3, attention_mask=t_1, position_bias=t_4, encoder_attention_mask=t_2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x1)
        t_4 = t_0[slice(None, 2, None)]
        t_4 = t_4[0]
        t_3 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_4(t_4, attention_mask=t_1, position_bias=t_3, encoder_attention_mask=t_2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x1)
        t_3 = t_0[slice(None, 2, None)]
        t_3 = t_3[0]
        t_4 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_5(t_3, attention_mask=t_1, position_bias=t_4, encoder_attention_mask=t_2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x1)
        t_4 = t_0[slice(None, 2, None)]
        t_4 = t_4[0]
        t_3 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_6(t_4, attention_mask=t_1, position_bias=t_3, encoder_attention_mask=t_2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x1)
        t_3 = t_0[slice(None, 2, None)]
        t_3 = t_3[0]
        t_4 = t_0[2]
        t_0 = t_0[3]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___318
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___320
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___322
        return list(flatten((x1, t_1, t_2, t_3, t_4, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition7(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[5]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[6]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:7'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.block.5',
                        'l_1': 'decoder.block.6'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[5] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[6] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___318 <=> x3
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___320 <=> x4
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___322 <=> x5
        x0, x1, x2, x3, x4, x5 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x1, position_bias=x4, encoder_attention_mask=x2, encoder_decoder_position_bias=x5, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_1(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___344
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___346
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___348
        return list(flatten((x0, x1, x2, t_2, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition8(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[7]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[8]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[9]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:8'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.block.7',
                        'l_1': 'decoder.block.8',
                        'l_2': 'decoder.block.9'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[7] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[8] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[9] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___344 <=> x3
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___346 <=> x4
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___348 <=> x5
        x0, x1, x2, x3, x4, x5 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x1, position_bias=x4, encoder_attention_mask=x2, encoder_decoder_position_bias=x5, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_1(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_2(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___383
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___385
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___387
        return list(flatten((x0, x1, x2, t_1, t_2, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition9(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[10]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[11]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:9'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.block.10',
                        'l_1': 'decoder.block.11',
                        'l_2': 'decoder.final_layer_norm',
                        'l_3': 'decoder.dropout'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[10] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[11] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___246 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___254 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___383 <=> x3
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___385 <=> x4
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___387 <=> x5
        x0, x1, x2, x3, x4, x5 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x1, position_bias=x4, encoder_attention_mask=x2, encoder_decoder_position_bias=x5, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_1(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_0 = t_0[slice(None, 2, None)]
        t_0 = t_0[0]
        t_0 = self.l_2(t_0)
        t_0 = self.l_3(t_0)
        t_0 = t_0 * 0.03608439182435161
        # Returning:
        # T5ForConditionalGeneration/Tensor::__mul___413
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition10(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/Linear[lm_head]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:10'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1]
        self.lookup = {'l_0': 'lm_head'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/Linear[lm_head] <=> self.l_0
        # input4 <=> labels
        # T5ForConditionalGeneration/Tensor::__mul___413 <=> x0
        labels, x0 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x0)
        t_1 = t_0.size(-1)
        t_1 = t_0.view(-1, t_1)
        t_0 = labels.view(-1)
        t_0 = torch.nn.functional.cross_entropy(t_1, t_0, weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
        # Returning:
        # T5ForConditionalGeneration/torch.nn.functional::cross_entropy_426
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


def traverse_model(module: nn.Module, depth: int, prefix: Optional[str] = None,
                   basic_blocks: Tuple[Type[nn.Module]] = (), full: bool = False) -> Iterator[
    Tuple[nn.Module, str, nn.Module, Optional[bool]]]:
    """
    iterate over model layers yielding the layer,layer_scope,encasing_module
    Parameters:
    -----------
    model:
        the model to iterate over
    depth:
        how far down in the model tree to go
    basic_blocks:
        a list of modules that if encountered will not be broken down
    full:
        whether to yield only layers specified by the depth and basic_block options or to yield all layers
    """
    if prefix is None:
        prefix = type(module).__name__

    for name, sub_module in module.named_children():
        scope = prefix + "/" + type(sub_module).__name__ + f"[{name}]"
        if len(list(sub_module.children())) == 0 or isinstance(sub_module, tuple(basic_blocks)) or depth == 0:
            if full:
                # TODO:
                # is_explicit_block_limit = len(list(sub_module.children())) != 0 and (isinstance(sub_module, tuple(basic_blocks)) or depth == 0)
                yield sub_module, scope, module, True

            else:
                yield sub_module, scope, module
        else:
            if full:
                yield sub_module, scope, module, False
            yield from traverse_model(sub_module, depth - 1, scope, basic_blocks, full)


def layerDict(model: nn.Module, depth=1000, basic_blocks=()) -> Dict[str, nn.Module]:
    return {s: l for l, s, _ in traverse_model(model, depth, basic_blocks=basic_blocks)}


def traverse_params_buffs(module: nn.Module, prefix: Optional[str] = None) -> Iterator[Tuple[torch.tensor, str]]:
    """
    iterate over model's buffers and parameters yielding obj,obj_scope

    Parameters:
    -----------
    model:
        the model to iterate over
    """
    if prefix is None:
        prefix = type(module).__name__

    # params
    for param_name, param in module.named_parameters(recurse=False):
        param_scope = f"{prefix}/{type(param).__name__}[{param_name}]"
        yield param, param_scope

    # buffs
    for buffer_name, buffer in module.named_buffers(recurse=False):
        buffer_scope = f"{prefix}/{type(buffer).__name__}[{buffer_name}]"
        yield buffer, buffer_scope

    # recurse
    for name, sub_module in module.named_children():
        yield from traverse_params_buffs(sub_module, prefix + "/" + type(sub_module).__name__ + f"[{name}]")


def tensorDict(model: nn.Module) -> OrderedDict[str, Tensor]:
    return collections.OrderedDict((s, t) for t, s in traverse_params_buffs(model))


def move_tensors(ts, device):
    def move(t):
        if isinstance(t, (nn.Module, Tensor)):
            return t.to(device)
        return t

    return nested_map(move, ts)


def nested_map(func, ts, full=False):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        return func(ts)
    elif isinstance(ts, (list, tuple, set)):
        return type(ts)(nested_map(func, t, full=full) for t in ts)
    elif isinstance(ts, dict):
        return {k: nested_map(func, v, full=full) for k, v in ts.items()}
    elif isinstance(ts, slice) and full:
        start = nested_map(func, ts.start, full=full)
        stop = nested_map(func, ts.stop, full=full)
        step = nested_map(func, ts.step, full=full)
        return slice(start, stop, step)
    return func(ts)


def flatten(ts):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        yield ts
    elif isinstance(ts, (list, tuple, set)):
        yield from chain(*[flatten(t) for t in ts])
    elif isinstance(ts, dict):
        yield from chain(*[flatten(t) for k, t in sorted(ts.items(), key=lambda t: t[0])])
    else:
        yield ts


def unflatten(xs, structure):
    return _unflatten(xs, structure)[0]


def _unflatten(xs, structure):
    if isinstance(structure, torch.Size):
        # torch.Size is subclass of tuple which is stupid
        return xs[0], 1

    if not isinstance(structure, (list, tuple, set, dict)):
        return xs[0], 1

    if isinstance(structure, (list, tuple, set)):
        offset = 0
        elements = []
        for s in structure:
            e, n = _unflatten(xs[offset:], s)
            elements.append(e)
            offset += n

        return type(structure)(elements), offset

    assert isinstance(structure, dict)
    offset = 0
    elements = dict()
    for k, v in sorted(structure.items(), key=lambda t: t[0]):
        e, n = _unflatten(xs[offset:], v)
        elements[k] = e
        offset += n

    return elements, offset


def state_dict(partition, *args, **kwargs):
    # we return the state dict of this part as it should be in the original model
    state = nn.Module.state_dict(partition, *args, **kwargs)
    lookup = partition.lookup
    result = dict()
    for k, v in state.items():
        if k in lookup:
            result[lookup[k]] = v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            result[new_k] = v
    return result


def load_state_dict(partition, state_dict, strict=True):
    reverse_lookup = {v: k for k, v in partition.lookup.items()}
    device = partition.device
    keys = list(partition.state_dict(None).keys())
    new_state = dict()
    for k in keys:
        if k in reverse_lookup:
            new_state[reverse_lookup[k]] = state_dict[k].to(device)
            continue
        idx = k.rfind(".")
        to_replace = k[:idx]
        if to_replace in reverse_lookup:
            key = reverse_lookup[to_replace] + k[idx:]
            new_state[key] = state_dict[k].to(device)
    nn.Module.load_state_dict(partition, new_state, strict=strict)


def named_buffers(partition, prefix='', recurse=True):
    # we return the named buffers of this part as it should be in the original model
    params = nn.Module.named_buffers(partition, prefix=prefix, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def named_parameters(partition, prefix='', recurse=True):
    # we return the named parameters of this part as it should be in the original model
    params = nn.Module.named_parameters(partition, prefix=prefix, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def cpu(partition):
    partition.device = torch.device('cpu')
    return nn.Module.cpu(partition)


def cuda(partition, device=None):
    if device is None:
        device = torch.cuda.current_device()
    partition.device = torch.device(device)
    return nn.Module.cuda(partition, partition.device)


def to(partition, *args, **kwargs):
    device = None
    if 'device' in kwargs:
        device = kwargs['device']
    elif 'tensor' in kwargs:
        device = kwargs['tensor'].device
    if args:
        if isinstance(args[0], (torch.device, int, str)):
            device = args[0]
        if torch.is_tensor(args[0]):
            device = args[0].device
    if not (device is None):
        partition.device = torch.device(device)
    return nn.Module.to(partition, *args, **kwargs)

model_args = {'model_name_or_path': 't5-base', 'max_seq_length': 512, 'answer_max_seq_length': 4, 'stateless_tied': True, 'lmhead': True, 'precompute_masks': False}

def lgt5_base_tied_lmheads_512_4_8p_bw12_squad1_mpipe():
    return dict(model_type='t5_stateless',
                model_name_or_path='t5-base',
                do_lower_case=False,
                output_past=False,
                stateless_tied=True,
                explicitly_set_dict={'return_dict': False, 'use_cache': False, 'output_only': True, 'output_attentions': False, 'precompute_masks': False, 'output_hidden_states': False},
                do_resize_token_embedding=True,
                )
    
"""analysis summary
-I- Printing Report
warnings:
Partition1 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___66 is not contiguous!
Partition2 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___111 is not contiguous!
Partition3 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___156 is not contiguous!
Partition4 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___186 is not contiguous!
Partition6 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___320 is not contiguous!
Partition7 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___346 is not contiguous!
Partition8 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___385 is not contiguous!
Number of nodes in Computation Graph: 427
Number of stages: 8
n_partitions:11, num_dummy_stages:3
unique_stages_on_same_gpu: [{0}, {1, 10}, {2, 4}, {3, 5}, {6}, {7}, {8}, {9}]
"stage_to_device_map": [0, 1, 2, 3, 2, 3, 4, 5, 6, 7, 1],
backward times include recomputation

Stage parameter count:
 {0: 24652800,
 1: 21238656,
 2: 21238272,
 3: 21238272,
 4: 14158848,
 5: 7080192,
 6: 47197824,
 7: 18878976,
 8: 28318464,
 9: 18879744,
 10: 24652800,
 'total': 247534848}

GPU parameter count:
 Number of Model Parameters 247.5M
{0: 24652800,
 1: 45891456,
 2: 35397120,
 3: 28318464,
 6: 47197824,
 7: 18878976,
 8: 28318464,
 9: 18879744,
 'total': 247534848}

real times are based on real measurements of execution time (with communication) of generated partitions ms
forward {0: 8.54, 1: 6.82, 2: 12.57, 3: 10.11, 6: 8.82, 7: 3.34, 8: 6.12, 9: 3.06}
backward {0: 10.1, 1: 22.91, 2: 21.02, 3: 16.76, 6: 27.7, 7: 6.55, 8: 10.54, 9: 7.19}

Analysis for T = (1-R)fwd + R*bwd:

Pipeline Slowdown: (compared to sequential execution with no communication, and same recompute policy)
forward 2.492
backward 2.136

Expected utilization by partition
forward {0: 0.0, 1: 0.35, 2: 0.62, 3: 0.59, 6: 0.68, 7: 0.25, 8: 0.47, 9: 0.24}
backward {0: 0.36, 1: 0.82, 2: 0.59, 3: 0.43, 6: 0.69, 7: 0.23, 8: 0.37, 9: 0.25}

worstcase: bwd: 27.698 fwd: 12.572
Expected speedup for 8 partitions is: 3.560
Assuming bandwidth of 12 GBps between GPUs

communication volumes size of activations of each partition
0: input size:'0.00 MB', recieve_time:'0.00 ms', out:'101.76 MB', send time:'8.48 ms'
1: input size:'3.17 MB', recieve_time:'0.26 ms', out:'28.32 MB', send time:'2.36 ms'
2: input size:'56.63 MB', recieve_time:'4.72 ms', out:'56.63 MB', send time:'4.72 ms'
3: input size:'56.63 MB', recieve_time:'4.72 ms', out:'31.46 MB', send time:'2.62 ms'
6: input size:'101.76 MB', recieve_time:'8.48 ms', out:'3.37 MB', send time:'0.28 ms'
7: input size:'3.37 MB', recieve_time:'0.28 ms', out:'3.37 MB', send time:'0.28 ms'
8: input size:'3.37 MB', recieve_time:'0.28 ms', out:'3.37 MB', send time:'0.28 ms'
9: input size:'3.37 MB', recieve_time:'0.28 ms', out:'0.02 MB', send time:'0.00 ms'

Compuatation Communication ratio (comp/(comp+comm)):
forward {0: 0.01, 1: 0.65, 2: 0.62, 3: 0.74, 6: 0.97, 7: 0.92, 8: 0.95, 9: 1.0} 
backward {0: 1.0, 1: 0.99, 2: 0.78, 3: 0.72, 6: 0.69, 7: 0.96, 8: 0.97, 9: 0.96}

Analysis for T = fwd + bwd:
 {'expected_compute_utilization': {0: 0.37,
                                  1: 0.98,
                                  2: 0.87,
                                  3: 0.7,
                                  6: 1.0,
                                  7: 0.34,
                                  8: 0.58,
                                  9: 0.36},
 'pipeline_no_comm': {0: 10.16,
                      1: 27.11,
                      2: 24.15,
                      3: 19.52,
                      6: 27.76,
                      7: 9.33,
                      8: 16.1,
                      9: 9.97,
                      'worstcase': 27.76},
 'pipeline_vs_seq_no_comm': 3.97,
 'pipeline_with_non_parallel_comm': {0: 18.64,
                                     1: 29.74,
                                     2: 33.59,
                                     3: 26.86,
                                     6: 36.52,
                                     7: 9.89,
                                     8: 16.66,
                                     9: 10.25,
                                     'worstcase': 36.52},
 'seq_no_comm_no_recomp': {0: 10.19,
                           1: 20.77,
                           2: 10.31,
                           3: 11.06,
                           4: 8.18,
                           5: 3.98,
                           6: 16.93,
                           7: 9.17,
                           8: 10.18,
                           9: 9.07,
                           10: 0.33}}

expected_speedup_compared_to_seq_no_recomp_no_comm: 2.736
Analysis max cuda memory used 0.60GB
"""